const auth=require('../middleware/authentication')
const labelController=require('../controller/labelController')
const express=require('express')
const router=express.Router()
router.post('/createlabel',auth.auth,labelController.labelControllerCreateLabel)
router.post('/getlabels',auth.auth,labelController.labelControllerGetLabels)
router.post('/deletelabel',auth.auth,labelController.labelControllerDeleteLabel)
router.post('/editlabelname',auth.auth,labelController.labelControllerEditLabelName)
router.post('/addnotetolabel',auth.auth,labelController.labelControllerAddNoteTolabel)
router.post('/removenotefromlabel',auth.auth,labelController.labelControllerRemoveNoteFromLabel)
module.exports=router